title: Ivodev Blog
author: Salahuddin Muhammad Iqbal
email: salahuddin.mi@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Blog about web development, natural language processing, and natural language generation.
show_excerpts: true # set to true to show excerpts on the homepage


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Salahuddin Muhammad Iqbal
  tagline: Make Machine Write
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: ivokun
    github:  ivokun
    linkedIn: in/ivokun
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed